[postgresql]
host=localhost
database=calval
user=psql
password=cs590password

[mongodb]
host=localhost
database=delisweet
collection=''
user=''
password=''
port=27017

[neo4j]
host=localhost
database=neo4j
user=neo4j
password=Neo4j123!
